Traceback (most recent call last):
  File "C:\Proyectos\Bbitbucket 365\SMS_Jermsoft 8.1\main.py", line 348, in Iniciar
    self.PuertoCOM = serial.Serial(port='COM22', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\serial\serialutil.py", line 171, in __init__
    self.open()
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM22': WindowsError(5, 'Acceso denegado.')
 - None - 0 - 29 Apr 16 12:39:22
Traceback (most recent call last):
  File "C:\Proyectos\Bbitbucket 365\SMS_Jermsoft 8.1\main.py", line 351, in Iniciar
    self.PuertoCOM = serial.Serial(port='COM22', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\serial\serialutil.py", line 171, in __init__
    self.open()
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM22': WindowsError(5, 'Acceso denegado.')
 - None - 0 - 29 Apr 16 13:49:54
Traceback (most recent call last):
  File "C:\Proyectos\Bbitbucket 365\SMS_Jermsoft 8.1\main.py", line 352, in Iniciar
    self.PuertoCOM = serial.Serial(port='COM22', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\serial\serialutil.py", line 171, in __init__
    self.open()
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM22': WindowsError(32, 'El proceso no tiene acceso al archivo porque est\xe1 siendo utilizado por otro proceso.')
 - None - 0 - 29 Apr 16 14:05:10
Traceback (most recent call last):
  File "C:\Proyectos\Bbitbucket 365\SMS_Jermsoft 8.1\main.py", line 356, in Iniciar
    self.PuertoCOM = serial.Serial(port='COM22', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\serial\serialutil.py", line 171, in __init__
    self.open()
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM22': WindowsError(5, 'Acceso denegado.')
 - None - 0 - 29 Apr 16 16:01:28
Traceback (most recent call last):
  File "C:\Proyectos\Bbitbucket 365\SMS_Jermsoft 8.1\main.py", line 366, in Iniciar
    self.PuertoCOM = serial.Serial(port='COM22', baudrate=921600, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, write_timeout=None, dsrdtr=False, inter_byte_timeout=None)
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\serial\serialutil.py", line 171, in __init__
    self.open()
  File "C:\Python\Python27\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM22': WindowsError(5, 'Acceso denegado.')
 - None - 0 - 29 Apr 16 17:15:12
